travis:
  secure:
    BINSTAR_TOKEN: IIsIEuuhb4Sdf/4l13ainqS26x6nuKub1wYwzxtFkH2aIuwRsvqDDOuW76EePeo7j8KmdXFuxmJk0TY+ABEuikxhTAhlqNZ4YkJECuKe7z6rkrqaPCGZxf2rOyNODAhr4eA8NRiKoTx2REWEDVt/ux1fwN3hju9usWP3KlLhx3It4SlUwA8ElIOhQVqG8rX/m+Pv8tAwe/DbHCoiZO3JTLaiZHYBPK5IUwQzza8rb4bH9rdE6opWEvbi+Sj4ha4KnU8s1cyY8TpF8Bewf0UVchSLbqWFFlADSczHc14s/8GopuwjbH9ZbT/+5hoIBSycYLvmsGXFk8i9oZNTeaqiAYqntS/tDEXV3ttO64U0vSJebT/if9keWf/UhzCozJgxjripel1/HCLIBByxUdb7sWkTD91sRHCEsN7Kw+8kTtbO8Qts2oF025pfINT7uDVyOi4Jy32xmBAaiLTGHg4lhjX0fQX9lBR9PnSs3Ves7+PpueqKqk0D+3VILra0ZsgedfUkdP8vOP8/NQuwkfcqgoDNCaAH65+UyJXb+j/4FC9xjiCdOIjQz1yt/6q0cj9UA3J3e0o03l/yOlWbdFUatO1pjXw9LmZBvs8VRFZiOXDC5zs2dlHxDw//55BAD8Rk9ST3uarD6ukaPKO0UUE5qydN2xzCxWHnsuNm0jX73Gk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
